version: '3'
services:

  #Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dr3
    container_name: app
    volumes: 
      - .:/var/www/
    ports: 
      - "9000:9000"
    networks:
      - laraveldockerize

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes: 
      - .:/var/www
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laraveldockerize

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laraveldockerize

#Docker Networks
networks:
  laraveldockerize:
    driver: bridge